name: CI Dev

on: 
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [ 12.8.6 ]

    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup OpenEdge
        uses: ./.github/actions/setup-openedge
        with:
          version: ${{ matrix.version }}
          dockerfile: Dockerfile-dev
            
      - name: Build docker image
        run: |
          docker build -f Dockerfile-dev -t openedge-pas:${{env.OPENEDGE_VERSION}} .
        
    
    